services:
  - type: web
    name: voice-inventory-manager
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 10000



