services:
  - type: web
    name: voice-inventory
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
    disks:
      - name: data
        mountPath: /opt/render/project/data
        sizeGB: 1
    preDeployCommand: |
      mkdir -p /opt/render/project/data
      echo "[]" > /opt/render/project/data/vendors.json
      echo "[]" > /opt/render/project/data/materials.json
      echo '[{"unit":"kg"},{"unit":"liters"},{"unit":"units"}]' > /opt/render/project/data/units.json
      echo "[]" > /opt/render/project/data/inventory.json